version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiemply-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - composer_cache:/root/.composer
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tiemply-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: tiemply-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  #   networks:
  #     - tiemply-network
  #   depends_on:
  #     - app

  db:
    image: mariadb:10.7
    container_name: tiemply-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD} # Asegúrate de que esta variable esté configurada
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/data/db
    networks:
      - tiemply-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tiemply_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}      
    networks:
      - tiemply-network

networks:
  tiemply-network:
    driver: bridge

volumes:
  composer_cache:
    driver: local
  mariadb-data:
    driver: local